OPEN DATA "C:\Users\Windows-7\Desktop\Projeto Agronegócio\Data.xls"
CALENDAR 2000 1 12
ALL 2013:11
DATA(FORMAT=XLS,ORG=COLUMNS) 2000:01 2013:11 BCB BCS BCM CAMR CAM TT PIB USA CHINA EU MUNDO
Log BCB / LBCB
Log BCS / LBCS
Log BCM / LBCM
Log CAMR / LCAMR
Log CAM / LCAM
Log TT / LTT
Log PIB / LPIB
Log USA / LUSA
Log CHINA / LCHINA
Log EU / LEU
Log MUNDO / LMUNDO
sou
@cats(lags=1,dettrend=cimean)
# LBCM LTT LPIB LMUNDO








